[package]
name = "jiraya"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.33.0"
rand = "*"
chrono = "0.4.33"
colored = "*"